export interface Restroom {
  id: number;
  name: string;
  position: [number, number];
  cleanliness: number;
  features: string[];
  paymentType: "Free" | "Paid";
  type: "Public" | "Private";
  gender: string[];
}

export const restrooms: Restroom[] = [
  {
    id: 1,
    name: "SM Mall of Asia CR",
    position: [14.5354, 120.9821],
    cleanliness: 4,
    features: ["Wheelchair Accessible", "Hand Dryer", "Soap Available"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female", "Gender-Neutral"],
  },
  {
    id: 2,
    name: "Robinsons Place Manila CR",
    position: [14.582, 120.9787],
    cleanliness: 3,
    features: ["Paper Towels", "Bidet"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 3,
    name: "Starbucks Ayala CR",
    position: [14.5507, 121.0137],
    cleanliness: 5,
    features: ["Soap Available", "Hand Dryer"],
    paymentType: "Paid",
    type: "Private",
    gender: ["Unisex"],
  },
  {
    id: 4,
    name: "LRT Central Station CR",
    position: [14.5895, 120.9812],
    cleanliness: 2,
    features: [],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 5,
    name: "Bonifacio High Street CR",
    position: [14.5534, 121.0247],
    cleanliness: 4,
    features: ["Wheelchair Accessible", "All-Gender"],
    paymentType: "Free",
    type: "Public",
    gender: ["All-Gender"],
  },
  {
    id: 6,
    name: "Greenbelt 3 CR",
    position: [14.5546, 121.0244],
    cleanliness: 5,
    features: ["Hand Dryer", "Soap Available", "Baby Changing Station"],
    paymentType: "Paid",
    type: "Public",
    gender: ["Male", "Female", "Unisex"],
  },
  {
    id: 7,
    name: "Ayala MRT Station CR",
    position: [14.5553, 121.0219],
    cleanliness: 3,
    features: ["Soap Available"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 8,
    name: "Shangri-La Hotel CR",
    position: [14.5543, 121.0455],
    cleanliness: 5,
    features: [
      "Luxury Amenities",
      "Hand Dryer",
      "Soap Available",
      "Baby Changing Station",
    ],
    paymentType: "Paid",
    type: "Private",
    gender: ["Unisex"],
  },
  {
    id: 9,
    name: "Glorietta 5 CR",
    position: [14.5531, 121.0211],
    cleanliness: 4,
    features: ["Wheelchair Accessible", "Paper Towels"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 10,
    name: "Trinoma Mall CR",
    position: [14.6573, 121.0325],
    cleanliness: 3,
    features: ["Soap Available", "Hand Dryer"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female", "Gender-Neutral"],
  },
  {
    id: 11,
    name: "UP Diliman Campus CR",
    position: [14.6567, 121.0742],
    cleanliness: 2,
    features: ["Basic Facilities"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 12,
    name: "Mall of Asia Arena CR",
    position: [14.5359, 120.9819],
    cleanliness: 4,
    features: ["Wheelchair Accessible", "Soap Available"],
    paymentType: "Paid",
    type: "Public",
    gender: ["All-Gender"],
  },
  {
    id: 13,
    name: "Century City Mall CR",
    position: [14.5551, 121.0223],
    cleanliness: 4,
    features: ["Hand Dryer", "Paper Towels"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
  {
    id: 14,
    name: "Power Plant Mall CR",
    position: [14.5742, 121.0491],
    cleanliness: 5,
    features: ["Luxury Amenities", "Baby Changing Station", "Soap Available"],
    paymentType: "Paid",
    type: "Private",
    gender: ["Unisex"],
  },
  {
    id: 15,
    name: "Ortigas MRT Station CR",
    position: [14.5821, 121.0596],
    cleanliness: 3,
    features: ["Soap Available"],
    paymentType: "Free",
    type: "Public",
    gender: ["Male", "Female"],
  },
];
